# Generated by Django 4.2.11 on 2024-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0004_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.TextField(default='No comments yet', max_length=200),
        ),
    ]
