# Generated by Django 4.2.11 on 2024-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='no comments', max_length=500),
        ),
    ]
