# Generated by Django 4.0.10 on 2024-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
